console.log("Nihil")
console.log("Nihil")
console.log("Nihil")
console.log("Nihil")
console.log("Nihil")
console.log("Nihil")
console.log("Nihil")
console.log("Nihil")
console.log("Kontol yang sangat besar")
